apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi8-page-tls
spec:
  secretName: multi8-page-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi8.page
  dnsNames:
    - multi8.page
    - www.multi8.page
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi8.page
          - www.multi8.page